### ISSUE TITLE
I have a hard time with building the skeleton...

### ISSUE THREAD

**Issue by nikolaus-online** [hkuhn42/openhab2.elements#1]
Hey there,

can you tell me whether or not this binding will still work with openHAB 2? I have a hard time compiling your code with Maven/Eclipse. Getting some weird errors.

Thanks for your effort!

Nikolaus\

**Comment by hkuhn42** [comment]
I actually developed it for an early version of openhab2. However after some major changes in oh2, my dev environment and my home installation broke down and i stopped using openhab2 some years ago. From what i read and hear, it probably will no longer work.  Heiko Scholtes actually wanted to take over maintainance of the plugin but i guess that did not work out... Sorry
